---
apiVersion: v1
kind: Service
metadata:
  name: spark-his
  labels:
    app: spark-his
spec:
  ports:
  - port: 18080
    targetPort: 18080
    name: web
  selector:
    app: spark-his
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-his
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-his
    spec:
      containers:
      - name: spark
        imagePullPolicy: IfNotPresent
        image: pilchard/spark
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 18080
          name: web
        command:
        - sh
        - -c
        - |
          /etc/init.d/spark-history-server start
          tail -f /var/log/spark/*
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf                         
        - name: spark
          mountPath: /etc/spark/conf 
        - name: hive
          mountPath: /etc/hive/conf
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
      - name: spark
        configMap:
          name: spark
      - name: hive
        configMap:
          name: hive
