apiVersion: v1
kind: Secret
metadata:
  name: registry-key
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxOTIuMTY4LjIxNi4xMjg6NTAwMCI6IHsKCQkJImF1dGgiOiAiZFc1MWMyVmtPbVZMU2pFdGRraGxUakU1ZFVweFFtMW1Za0ZKVldaMmF6WlBhR1o1Umt4RlgyUTFSVmxIZEVsdk5HTT0iLAoJCQkiZW1haWwiOiAidW51c2VkIgoJCX0KCX0KfQ==

type: kubernetes.io/dockerconfigjson
