apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-sq-config
data:
  # basic config options.
  config.http-cache-dir: /cache/httpcache
  config.organization: kubernetes
  config.project: kubernetes
  config.pr-mungers: blunderbuss,lgtm-after-commit,cherrypick-auto-approve,label-unapproved-picks,needs-rebase,path-label,size,stale-pending-ci,stale-green-ci,block-path,release-note-label,comment-deleter,submit-queue,issue-cacher,flake-manager,old-test-getter,close-stale-pr,docs-need-no-retest,nag-flake-issues
  config.state: open
  config.token-file: /etc/secret-volume/token

  # test-options feature options.
  test-options.required-retest-contexts: "\"Jenkins GCE e2e\",\"Jenkins unit/integration\",\"Jenkins verification\",\"Jenkins GCE Node e2e\",\"Jenkins Kubemark GCE e2e\",\"Jenkins GCE etcd3 e2e\""

  # submit-queue options.
  submit-queue.required-contexts: "Jenkins GCE Node e2e"
  submit-queue.nonblocking-jenkins-jobs: "\
    ci-kubernetes-e2e-aws,\
    ci-kubernetes-e2e-gce-examples,\
    ci-kubernetes-e2e-gce-federation,\
    ci-kubernetes-e2e-gce-multizone,\
    ci-kubernetes-e2e-gce-scalability,\
    ci-kubernetes-e2e-gci-gce-alpha-features-release-1.4,\
    ci-kubernetes-e2e-gci-gce-autoscaling,\
    ci-kubernetes-e2e-gci-gce-autoscaling-migs,\
    ci-kubernetes-e2e-gci-gce-es-logging,\
    ci-kubernetes-e2e-gci-gce-etcd3,\
    ci-kubernetes-e2e-gci-gce-examples,\
    ci-kubernetes-e2e-gci-gce-federation,\
    ci-kubernetes-e2e-gci-gce-flannel,\
    ci-kubernetes-e2e-gci-gce-ingress,\
    ci-kubernetes-e2e-gci-gce-ingress-release-1.4,\
    ci-kubernetes-e2e-gci-gce-kubenet,\
    ci-kubernetes-e2e-gci-gce-petset,\
    ci-kubernetes-e2e-gci-gce-proto,\
    ci-kubernetes-e2e-gci-gce-reboot,\
    ci-kubernetes-e2e-gci-gce-reboot-release-1.4,\
    ci-kubernetes-e2e-gci-gce-release-1.4,\
    ci-kubernetes-e2e-gci-gce-scalability,\
    ci-kubernetes-e2e-gci-gce-scalability-release-1.4,\
    ci-kubernetes-e2e-gci-gce-serial,\
    ci-kubernetes-e2e-gci-gce-serial-release-1.4,\
    ci-kubernetes-e2e-gci-gce-slow-release-1.4,\
    ci-kubernetes-kubemark-5-gce,\
    continuous-e2e-docker-validation-gci,\
    kubelet-serial-gce-e2e-ci,\
    kuberentes-e2e-gce-enormous-deploy,\
    kuberentes-e2e-gce-enormous-teardown,\
    kubernetes-cross-build,\
    kubernetes-e2e-gce-enormous-cluster,\
    kubernetes-e2e-gce-serial,\
    kubernetes-e2e-gci-gke-alpha-features,\
    kubernetes-e2e-gci-gke-autoscaling,\
    kubernetes-e2e-gci-gke-ingress,\
    kubernetes-e2e-gci-gke-ingress-release-1.4,\
    kubernetes-e2e-gci-gke-multizone,\
    kubernetes-e2e-gci-gke-pre-release,\
    kubernetes-e2e-gci-gke-prod,\
    kubernetes-e2e-gci-gke-prod-parallel,\
    kubernetes-e2e-gci-gke-prod-smoke,\
    kubernetes-e2e-gci-gke-reboot,\
    kubernetes-e2e-gci-gke-reboot-release-1.4,\
    kubernetes-e2e-gci-gke-release-1.4,\
    kubernetes-e2e-gci-gke-serial,\
    kubernetes-e2e-gci-gke-serial-release-1.4,\
    kubernetes-e2e-gci-gke-slow-release-1.4,\
    kubernetes-e2e-gci-gke-staging,\
    kubernetes-e2e-gci-gke-staging-parallel,\
    kubernetes-e2e-gci-gke-subnet,\
    kubernetes-e2e-gci-gke-test,\
    kubernetes-e2e-gci-gke-updown,\
    kubernetes-e2e-gke-large-cluster,\
    kubernetes-e2e-gke-serial,\
    kubernetes-e2e-gke-staging,\
    kubernetes-e2e-gke-staging-parallel,\
    kubernetes-e2e-gke-test,\
    kubernetes-garbagecollector-gci-feature,\
    kubernetes-soak-continuous-e2e-gce,\
    kubernetes-soak-continuous-e2e-gci-gce-1.4,\
    kubernetes-soak-continuous-e2e-gke,\
    kubernetes-soak-continuous-e2e-gke-gci,\
    kubernetes-soak-weekly-deploy-gci-gce-1.4,\
    kubernetes-soak-weekly-deploy-gke-gci,\
    kubernetes-e2e-kops-aws-updown"
  submit-queue.jenkins-jobs: "\
    ci-kubernetes-e2e-gce-etcd3,\
    ci-kubernetes-e2e-gci-gce,\
    ci-kubernetes-e2e-gci-gce-slow,\
    ci-kubernetes-kubemark-500-gce,\
    ci-kubernetes-test-go,\
    ci-kubernetes-verify-master,\
    kubelet-gce-e2e-ci,\
    kubernetes-build,\
    kubernetes-e2e-gci-gke,\
    kubernetes-e2e-gci-gke-slow,\
    kubernetes-e2e-kops-aws"
  submit-queue.presubmit-jobs: "\
    kubernetes-pull-build-test-e2e-gce,\
    kubernetes-pull-build-test-e2e-gke,\
    kubernetes-pull-build-test-federation-e2e-gce,\
    node-pull-build-e2e-test,\
    kubernetes-pull-build-test-gci-e2e-gce,\
    kubernetes-pull-build-test-gci-e2e-gke,\
    kubernetes-pull-build-test-gci-kubemark-e2e-gce"
  submit-queue.weak-stable-jobs: "\"\""
  submit-queue.do-not-merge-milestones: "next-candidate,v1.6,"
  submit-queue.admin-port: "9999"
  submit-queue.chart-url: http://storage.googleapis.com/kubernetes-test-history/k8s-queue-health.svg
  submit-queue.history-url: http://storage.googleapis.com/kubernetes-test-history/static/index.html

  # options used by the GCS feature.
  gcs.gcs-bucket: kubernetes-jenkins
  gcs.gcs-logs-dir: logs
  gcs.pull-logs-dir: pr-logs
  gcs.pull-key: pull

  # munger specific options.
  path-label.path-label-config: path-label.txt
  block-path.block-path-config: block-path.yaml
  gitrepo.repo-dir: /gitrepos
  gitrepo.enable-md-yaml: "false"
  flake-manager.test-owners-csv: /gitrepos/kubernetes/test/test_owners.csv
  old-test-getter.number-of-old-test-results: "5"
  assign-fixes.fixes-issue-reassign: "false"
  blunderbuss.blunderbuss-reassign: "false"
  size.generated-files-config: .generated-files
  check-labels.label-file: "/gitrepos/kubernetes/labels.yaml"
  issue-categorizer.triager-url: "http://issue-triager-service:5000"
  cla.cla-status-context: ""
  alias.alias-file: "/gitrepos/kubernetes/OWNERS_ALIASES"
