apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: submit-queue
    target-repo: kubernetes
  name: kubernetes-cache
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: kubernetes-cache
    fsType: ext4
