apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
spec:
  rules:
  - host: grafana.ludun.xin
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hue
  namespace: default
spec:
  rules:
  - host: hue.ludun.xin
    http:
      paths:
      - backend:
          serviceName: hue
          servicePort: 8888
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard
  namespace: kube-system
spec:
  rules:
  - host: dashboard.ludun.xin
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
spec:
  rules:
  - host: prometheus.ludun.xin
    http:
      paths:
      - backend:
          serviceName: prometheus-k8s
          servicePort: 9090

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  rules:
  - host: alertmanager.ludun.xin
    http:
      paths:
      - backend:
          serviceName: alertmanager-main
          servicePort: 9093


