---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        tier: web
    spec:
      containers:
      - name: nginx
        image: 192.168.216.128:5000/web/nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    tier: web
