apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: submit-queue
    target-repo: docs
  name: docs-cache
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: docs-cache
    fsType: ext4
