apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-discovery
    k8s-app: kube-discovery
    kubernetes.io/cluster-service: "true"
    name: kube-discovery
    pod-template-hash: "1150918428"
    tier: node
  name: kube-discovery
  namespace: kube-system
spec:
  containers:
  - command:
    - /usr/local/bin/kube-discovery
    image: gcr.io/google_containers/kube-discovery-amd64:1.0
    imagePullPolicy: IfNotPresent
    name: kube-discovery
    ports:
    - containerPort: 9898
      hostPort: 9898
      name: http
      protocol: TCP
    volumeMounts:
    - mountPath: /tmp/secret
      name: clusterinfo
      readOnly: true
    resources: {}
    securityContext:
      seLinuxOptions:
        type: unconfined_t
    terminationMessagePath: /dev/termination-log
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - name: clusterinfo
    secret:
      defaultMode: 420
      secretName: clusterinfo


