apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-dns
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    name: kube-dns
    tier: node
  name: kube-dns
  namespace: kube-system
spec:
  containers:
  - args:
    - --domain=cluster.local
    - --dns-port=10053
    image: gcr.io/google_containers/kubedns-amd64:1.7
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 1
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: kube-dns
    ports:
    - containerPort: 10053
      name: dns-local
      protocol: UDP
    - containerPort: 10053
      name: dns-tcp-local
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readiness
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 100m
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 170Mi
    terminationMessagePath: /dev/termination-log
  - args:
    - --cache-size=1000
    - --no-resolv
    - --server=127.0.0.1#10053
    image: gcr.io/google_containers/kube-dnsmasq-amd64:1.3
    imagePullPolicy: IfNotPresent
    name: dnsmasq
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 170Mi
    terminationMessagePath: /dev/termination-log
  - args:
    - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:53 >/dev/null &&
      nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
    - -port=8080
    - -quiet
    image: gcr.io/google_containers/exechealthz-amd64:1.1
    imagePullPolicy: IfNotPresent
    name: healthz
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 10m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
  dnsPolicy: Default
  nodeName: ma
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
