apiVersion: v1
kind: Service
metadata:
  name: sentry
  labels:
    app: sentry
spec:
  ports:
  - port: 8038
    targetPort: 8038
    name: sentry
  selector:
    app: sentry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry
    spec:
      containers:
      - name: sentry
        imagePullPolicy: Always
        image: docker.io/pilchard/solr
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 8038
          name: rpc
        livenessProbe:
          tcpSocket:
            port: 8038
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        command:
        - sh
        - -c
        - |
          su - sentry -s /bin/bash -c "sentry --command service --conffile /etc/sentry/conf/sentry-site.xml 2>&1"
        volumeMounts:
        - name: sentry
          mountPath: /etc/sentry/conf 
      volumes:
      - name: sentry
        configMap:
          name: sentry

