---
apiVersion: v1
kind: Service
metadata:
  name: httpfs
  labels:
    app: httpfs
spec:
  ports:
  - port: 14000
    targetPort: 14000
    name: httpfs
  selector:
    app: httpfs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpfs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpfs
    spec:
      containers:
      - name: httpfs
        imagePullPolicy: Always
        image: docker.io/pilchard/hadoop
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 14000
          name: rpc
        env:
        - name : HADOOP_HEAPSIZE
          value: "1000"          
        command:
        - sh
        - -c
        - |
          /etc/init.d/hadoop-httpfs start
          tail -f /var/log/hadoop-httpfs/*
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf                                   
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
          
