---
apiVersion: v1
kind: Service
metadata:
  name: metastore
  labels:
    app: metastore
spec:
  ports:
  - port: 9803
    name: metastore
  clusterIP: None
  selector:
    app: metastore
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: metastore
spec:
  serviceName: metastore
  replicas: 1
  template:
    metadata:
      labels:
        app: metastore
    spec:
      containers:
      - name: metastore
        imagePullPolicy: IfNotPresent
        image: pilchard/hive
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 9803
          name: rpc
        env:
        - name : HADOOP_HEAPSIZE
          value: "1000"          
        command:
        - sh
        - -c
        - |
          /etc/init.d/hive-metastore start
          tail -f /var/log/hive/*
        volumeMounts:
        - name: hive
          mountPath: /etc/hive/conf                                     
        - name: hadoop
          mountPath: /etc/hadoop/conf 
      volumes:
      - name: hive
        configMap:
          name: hive
      - name: hadoop
        configMap:
          name: hadoop
          
