---
apiVersion: v1
kind: Service
metadata:
  name: metastore
  labels:
    app: metastore
spec:
  ports:
  - port: 9803
    name: metastore
  clusterIP: None
  selector:
    app: metastore
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: metastore
spec:
  serviceName: metastore
  replicas: 1
  template:
    metadata:
      labels:
        app: metastore
    spec:
      containers:
      - name: metastore
        imagePullPolicy: Always
        image: docker.io/pilchard/hive
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 9803
          name: rpc
        livenessProbe:
          tcpSocket:
            port: 9083 
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name : HADOOP_HEAPSIZE
          value: "1000"          
        - name : HADOOP_OPTS
          value: "-Dhive.log.dir=/var/log/hive/ -Dhive.log.file=hive-server2.log -Dhive.root.logger=INFO,console"
        command:
        - sh
        - -c
        - |
          su -s /bin/bash hive -c "hive --service metastore"
        volumeMounts:
        - name: hive
          mountPath: /etc/hive/conf                                     
        - name: hadoop
          mountPath: /etc/hadoop/conf 
      volumes:
      - name: hive
        configMap:
          name: hive
      - name: hadoop
        configMap:
          name: hadoop

          
