---
apiVersion: v1
kind: Service
metadata:
  name: hiveserver2
  labels:
    app: hiveserver2
spec:
  ports:
  - port: 10000
    targetPort: 10000
    name: hiveserver2
  selector:
    app: hiveserver2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hiveserver2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hiveserver2
    spec:
      containers:
      - name: hiveserver2
        imagePullPolicy: IfNotPresent
        image: pilchard/hive
        resources:
          requests:
            cpu: "100m"
#        livenessProbe:
#          tcpSocket:
#            port: 10000
#          initialDelaySeconds: 15
#          periodSeconds: 15
#          timeoutSeconds: 5
        env:
        - name : HADOOP_HEAPSIZE
          value: "1000"   
        - name : HADOOP_OPTS
          value: "-Dhive.log.dir=/var/log/hive/ -Dhive.log.file=hive-server2.log -Dhive.log.threshold=INFO"
        ports:
        - containerPort: 10000
          name: rpc
        command:
        - sh
        - -c
        - |
          hdfs dfs -ls /user/hive || su -s /bin/bash hdfs -c "hdfs dfs -mkdir -p /user/hive/warehouse && hdfs dfs -chmod -R 1777 /user && hdfs dfs -chown -R hive:hive /user/hive && hdfs dfs -chmod 1777 /user/hive/warehouse"
          su -s /bin/bash hive -c "hive --service hiveserver2 2>&1"
        volumeMounts:
        - name: hive
          mountPath: /etc/hive/conf   
        - name: hadoop
          mountPath: /etc/hadoop/conf                                   
      volumes:
      - name: hive
        configMap:
          name: hive
      - name: hadoop
        configMap:
          name: hadoop
          
