---
apiVersion: v1
kind: Service
metadata:
  name: metastore
  labels:
    app: metastore
spec:
  ports:
  - port: 9803
    targetPort: 9083
    name: metastore
  selector:
    app: metastore
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metastore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: metastore
    spec:
      containers:
      - name: metastore
        imagePullPolicy: IfNotPresent
        image: pilchard/hive
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 9803
          name: rpc
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"          
        command:
        - sh
        - -c
        - |
          mkdir -p /hive/logs
          nohup hive --service metastore 2>&1 > /hive/logs/hive-metastore.log &
          tail -f /hive/logs/hive-metastore.log
        volumeMounts:
        - name: hive
          mountPath: /hive/conf                                     
        - name: hadoop
          mountPath: /hadoop/etc/hadoop                                   
      volumes:
      - name: hive
        configMap:
          name: hive
      - name: hadoop
        configMap:
          name: hadoop
          