---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-serviceaccount
  namespace: gitlab
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitlab-serviceaccount
    namespace: gitlab
