apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: submit-queue
    target-repo: contrib
  name: contrib-cache
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: contrib-cache
    fsType: ext4
