kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: submit-queue
    target-repo: contrib
  name: contrib-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
