apiVersion: v1
kind: Service
metadata:
  labels:
    app: submit-queue
    target-repo: contrib
  name: contrib-sq-status
spec:
  ports:
  - name: status
    port: 80
    targetPort: status
  selector:
    app: submit-queue
    target-repo: contrib
  type: NodePort
