apiVersion: v1
kind: Service
metadata:
  name: statestore
  labels:
    app: statestore
spec:
  ports:
  - port: 24000
    targetPort: 24000
    name: statestore
  - port: 25010
    targetPort: 25010
    name: web
  selector:
    app: statestore
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statestore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: statestore
    spec:
      containers:
      - name: statestore
        imagePullPolicy: Always
        image: docker.io/pilchard/impala
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 24000
          name: rpc
        livenessProbe:
          tcpSocket:
            port: 25010
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"          
        command:
        - sh
        - -c
        - |
          sed -i "s/search/search hdfs-dn.default.svc.cluster.local catalog.default.svc.cluster.local/g" /etc/resolv.conf
          echo "nameserver 10.96.0.10" > /etc/resolv.conf
          echo "search hdfs-dn.default.svc.cluster.local catalog.default.svc.cluster.local default.svc.cluster.local svc.cluster.local cluster.local us-east-2.compute.internal" >> /etc/resolv.conf
          echo "options ndots:5" >> /etc/resolv.conf

          /etc/init.d/impala-state-store start
          tail -f /var/log/impala/*
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf                         
        - name: impala 
          mountPath: /etc/impala/conf
        - name: hive
          mountPath: /etc/hive/conf
        - name: hbase
          mountPath: /etc/hbase/conf
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
      - name: hive
        configMap:
          name: hive
      - name: hbase
        configMap:
          name: hbase
      - name: impala 
        configMap:
          name: impala 

