---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-jn
  labels:
    app: hdfs-jn
spec:
  ports:
  - port: 8480
    name: web
  - port: 8485
    name: rpc
  clusterIP: None
  selector:
    app: jn
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jn
spec:
  serviceName: hdfs-jn
  replicas: 3
  template:
    metadata:
      labels:
        app: jn
    spec:
      containers:
      - name: hadoop
        imagePullPolicy: IfNotPresent
        image: pilchard/hadoop:2.7.3
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 8480
          name: web
        - containerPort: 8485
          name: rpc
        command:
        - sh
        - -c
        - export HADOOP_HEAPSIZE="200m"
        - hdfs journalnode
        volumeMounts:
        - name: hadoop
          mountPath: /hadoop/etc/hadoop  
        - name: dfs-jn
          mountPath: /data/1/dfs/jn/                          
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
  volumeClaimTemplates:
  - metadata:
      name: dfs-jn
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi