---
apiVersion: v1
kind: Service
metadata:
  name: yarn-nm
  labels:
    app: yarn-nm
spec:
  ports:
  - port: 8042
    name: web
  clusterIP: None
  selector:
    app: nm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nm
spec:
  serviceName: yarn-nm
  replicas: 1
  template:
    metadata:
      labels:
        app: nm
    spec:
      containers:
      - name: hadoop
        imagePullPolicy: IfNotPresent
        image: pilchard/hadoop
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 8042
          name: web
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"          
        command:
        - sh
        - -c
        - yarn nodemanager
        volumeMounts:
        - name: hadoop
          mountPath: /hadoop/etc/hadoop                            
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
