---
apiVersion: v1
kind: Service
metadata:
  name: mapred-job
  labels:
    app: mapred-job
spec:
  ports:
  - port: 19888
    name: web
  - port: 10020
    name: rpc-1
  - port: 10033
    name: rpc-2         
  clusterIP: None
  selector:
    app: job
---
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: job
spec:
  serviceName: mapred-job
  replicas: 1
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: hadoop
        imagePullPolicy: IfNotPresent
        image: pilchard/hadoop
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 19888
          name: web
        - containerPort: 10020
          name: rpc-1
        - containerPort: 10033
          name: rpc-2
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"                  
        command:
        - sh
        - -c
        - mapred historyserver
        volumeMounts:
        - name: hadoop
          mountPath: /hadoop/etc/hadoop                          
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
