---
apiVersion: v1
kind: Service
metadata:
  name: yarn-rm
  labels:
    app: yarn-rm
spec:
  ports:
  - port: 8088
    name: web
  - port: 8033
    name: rpc-1
  - port: 8031
    name: rpc-2
  - port: 8032
    name: rpc-3          
  clusterIP: None
  selector:
    app: rm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rm
spec:
  serviceName: yarn-rm
  replicas: 2
  template:
    metadata:
      labels:
        app: rm
    spec:
      containers:
      - name: hadoop
        imagePullPolicy: Always
        image: docker.io/pilchard/hadoop
        livenessProbe:
          tcpSocket:
            port: 8088
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 8032
          name: rpc-1
        - containerPort: 8031
          name: rpc-2
        - containerPort: 8033
          name: rpc-3   
        - containerPort: 8088
          name: web     
        livenessProbe:
          tcpSocket:
            port: 8088
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name : HADOOP_HEAPSIZE
          value: "1000"                      
        command:
        - su
        - -s 
        - /bin/bash
        - yarn
        - -c
        - |
          . /etc/default/hadoop && yarn resourcemanager
          #/etc/init.d/hadoop-yarn-resourcemanager start
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf                            
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
