---
apiVersion: v1
kind: Service
metadata:
  name: yarn-tl
  labels:
    app: yarn-tl
spec:
  ports:
  - port: 8188
    name: web
  - port: 10020
    name: rpc-1
  clusterIP: None
  selector:
    app: tl
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: tl
spec:
  serviceName: yarn-tl
  replicas: 1
  template:
    metadata:
      labels:
        app: tl
    spec:
      containers:
      - name: hadoop
        imagePullPolicy: Always 
        image: docker.io/pilchard/hadoop
        livenessProbe:
          httpGet:
            path: /
            port: 8188
            httpHeaders:
              - name: X-Custom-Header
                value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 15
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 8188
          name: web
        - containerPort: 10020
          name: rpc-2
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"                      
        command:
        - sh
        - -c
        - su -s /bin/bash yarn -c "yarn timelineserver"
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
