---
apiVersion: v1
kind: Service
metadata:
  name: mapred-job
  labels:
    app: mapred-job
spec:
  ports:
  - port: 19888
    name: web
  - port: 10020
    name: rpc-1
  - port: 10033
    name: rpc-2         
  clusterIP: None
  selector:
    app: job
---
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: job
spec:
  serviceName: mapred-job
  replicas: 1
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: hadoop
        imagePullPolicy: Always
        image: pilchard/hadoop
#        resources:
#          requests:
#            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 19888
            httpHeaders:
              - name: X-Custom-Header
                value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        ports:
        - containerPort: 19888
          name: web
        - containerPort: 10020
          name: rpc-1
        - containerPort: 10033
          name: rpc-2
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"                  
        command:
        - sh
        - -c
        - |
          /etc/init.d/hadoop-mapreduce-historyserver start
          tail -f /var/log/hadoop-mapreduce/*
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf                         
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
