---
apiVersion: v1
kind: Service
metadata:
  name: yarn-ps
  labels:
    app: yarn-ps
spec:
  ports:
  - port: 8089
    name: web
  clusterIP: None
  selector:
    app: ps
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ps
spec:
  serviceName: yarn-ps
  replicas: 1
  template:
    metadata:
      labels:
        app: ps
    spec:
      containers:
      - name: hadoop
        imagePullPolicy: IfNotPresent
        image: pilchard/hadoop
#        resources:
#          requests:
#            cpu: "100m"
#       readinessProbe:
#         httpGet:
#           path: /
#           port: 8089
#           httpHeaders:
#             - name: X-Custom-Header
#               value: Awesome
#         initialDelaySeconds: 15
#         periodSeconds: 15
#         timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8089
            httpHeaders:
              - name: X-Custom-Header
                value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        ports:
        - containerPort: 8089
          name: web     
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"                      
        command:
        - sh
        - -c
        - |
          #/etc/init.d/hadoop-yarn-proxyserver start
          su -s /bin/bash yarn -c "yarn proxyserver"
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
