apiVersion: v1
kind: Service
metadata:
  name: hue
  labels:
    app: hue
spec:
  ports:
  - port: 8888
    targetPort: 8888
    name: hue
  selector:
    app: hue
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
      - name: hue
        imagePullPolicy: IfNotPresent
        image: pilchard/hue
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 8888
          name: rpc
        livenessProbe:
          tcpSocket:
            port: 8888 
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name: SOLR_ZK_ENSEMBLE
          value: "zk-0.zk-headless:2181,zk-1.zk-headless:2181,zk-2.zk-headless:2181/solr"          
        - name: SOLR_HDFS_HOME
          value: "hdfs://hdfscluster/solr"
        command:
        - sh
        - -c
        - |
          echo "SOLR_ZK_ENSEMBLE=$SOLR_ZK_ENSEMBLE" >> /etc/default/solr
          echo "SOLR_HDFS_HOME=$SOLR_HDFS_HOME" >> /etc/default/solr
          /etc/init.d/hue start
          sleep 5
          tail -f /var/log/hue/*
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf                         
        - name: hue
          mountPath: /etc/hue/conf 
        - name: hive
          mountPath: /etc/hive/conf
        - name: hbase
          mountPath: /etc/hbase/conf
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
      - name: hive
        configMap:
          name: hive
      - name: hbase
        configMap:
          name: hbase
      - name: hue
        configMap:
          name: hue

