apiVersion: v1
kind: Service
metadata:
  name: hue
  labels:
    app: hue
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    name: hue
  selector:
    app: hue
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
      - name: hue
        imagePullPolicy: IfNotPresent
        image: pilchard/hue
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 8888
          name: rpc
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"          
        command:
        - sh
        - -c
        - |
          /etc/init.d/hue start
          tail -f /var/log/hue/*
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf                         
        - name: hue
          mountPath: /etc/hue/conf 
        - name: hive
          mountPath: /etc/hive/conf
        - name: hbase
          mountPath: /etc/hbase/conf
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
      - name: hive
        configMap:
          name: hive
      - name: hbase
        configMap:
          name: hbase
      - name: hue
        configMap:
          name: hue

