apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-system
  labels:
    component: elasticsearch
    role: kibana
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        component: elasticsearch
        role: kibana 
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      - name: es-client
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: kibana 
        imagePullPolicy: Always
        env:
        - name: "ELASTICSEARCH_URL"
          value: "http://elasticsearch:9200" 
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
