---
apiVersion: v1
kind: Service
metadata:
  name: hbase-thrift2
  labels:
    app: hbase-thrift2
spec:
  ports:
  - port: 9090
    name: rpc
  - port: 9095
    name: web
  clusterIP: None
  selector:
    app: hbase-thrift2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: thrift2
spec:
  serviceName: hbase-thrift2
  replicas: 1
  template:
    metadata:
      labels:
        app: hbase-thrift2 
    spec:
      containers:
      - name: hbase
        imagePullPolicy: IfNotPresent
        image: harisekhon/hbase
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 9090
          name: rpc
        - containerPort: 9095
          name: web
        env:
        - name : HBASE_HEAPSIZE
          value: "200"          
        command:
        - sh
        - -c
        - |
          mkdir -p /hbase/logs
          nohup hbase thrift2 start 2>&1 >/hbase/logs/hbase-thrift2.log &
          tail -f /hbase/logs/hbase-thrift2.log
        volumeMounts:
        - name: hbase
          mountPath: /hbase/conf                                     
      volumes:
      - name: hbase
        configMap:
          name: hbase
