---
apiVersion: v1
kind: Service
metadata:
  name: hbase-thrift
  labels:
    app: hbase-thrift
spec:
  ports:
  - port: 9090
    name: rpc
  - port: 9095
    name: web
  clusterIP: None
  selector:
    app: thrift
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: thrift
spec:
  serviceName: hbase-thrift
  replicas: 1
  template:
    metadata:
      labels:
        app: thrift
    spec:
      containers:
      - name: hbase
        imagePullPolicy: IfNotPresent
        image: pilchard/hbase
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 9090
          name: rpc
        - containerPort: 9095
          name: web
        env:
        - name : HBASE_HEAPSIZE
          value: "200"          
        - name : KRB5_CONFIG
          value: "/etc/kerberos/conf/krb5.conf"          
        command:
        - sh
        - -c
        - |
          echo "hbase - nofile  32768" > /etc/security/limits.d/hbase.conf
          /etc/init.d/hbase-thrift start
          tail -f /var/log/hbase/*
        volumeMounts:
        - name: hbase
          mountPath: /etc/hbase/conf                                     
        - name: kerberos
          mountPath: /etc/kerberos/conf                                     
      volumes:
      - name: hbase
        configMap:
          name: hbase
      - name: kerberos
        configMap:
          name: kerberos
