---
apiVersion: v1
kind: Service
metadata:
  name: hbase-ma
  labels:
    app: hbase-ma
spec:
  ports:
  - port: 16000
    name: rpc
  - port: 16010
    name: web
  clusterIP: None
  selector:
    app: ma
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ma
spec:
  serviceName: hbase-ma
  replicas: 2
  template:
    metadata:
      labels:
        app: ma
    spec:
      containers:
      - name: hbase
        imagePullPolicy: Always
        image: pilchard/hbase
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 60000
          name: rpc
        - containerPort: 60010
          name: web
        livenessProbe:
          httpGet:
            path: /
            port: 60010
            httpHeaders:
              - name: X-Custom-Header
                value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name : HBASE_HEAPSIZE
          value: "1000"          
        command:
        - sh
        - -c
        - |
          echo "hbase - nofile  32768" > /etc/security/limits.d/hbase.conf
          hdfs dfs -ls /hbase || su -s /bin/bash - hdfs -c "hdfs dfs -mkdir /hbase && hdfs dfs -chown -R hbase:hbase /hbase"
          su -s /bin/bash hbase -c "hbase master start"
        volumeMounts:
        - name: hbase
          mountPath: /etc/hbase/conf          
        - name: hadoop
          mountPath: /etc/hadoop/conf                           
      volumes:
      - name: hbase
        configMap:
          name: hbase
      - name: hadoop
        configMap:
          name: hadoop 
