---
apiVersion: v1
kind: Service
metadata:
  name: hbase-ma
  labels:
    app: hbase-ma
spec:
  ports:
  - port: 16000
    name: rpc
  - port: 16010
    name: web
  clusterIP: None
  selector:
    app: ma
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ma
spec:
  serviceName: hbase-ma
  replicas: 2
  template:
    metadata:
      labels:
        app: ma
    spec:
      containers:
      - name: hbase
        imagePullPolicy: IfNotPresent
        image: pilchard/hbase
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 16000
          name: rpc
        - containerPort: 16010
          name: web
        env:
        - name : HBASE_HEAPSIZE
          value: "500"          
        command:
        - sh
        - -c
        - |
          mkdir -p /hbase/logs
          hbase master start 2>&1 | tee -a /hbase/logs/hbase-master.log
        volumeMounts:
        - name: hbase
          mountPath: /hbase/conf                                     
      volumes:
      - name: hbase
        configMap:
          name: hbase
          
