---
apiVersion: v1
kind: Service
metadata:
  name: hbase-re
  labels:
    app: hbase-re
spec:
  ports:
  - port: 8080
    name: rpc
  - port: 8085
    name: web
  clusterIP: None
  selector:
    app: re
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: re
spec:
  serviceName: hbase-re
  replicas: 1
  template:
    metadata:
      labels:
        app: re
    spec:
      containers:
      - name: hbase
        imagePullPolicy: IfNotPresent
        image: harisekhon/hbase
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 8080
          name: rpc
        - containerPort: 8085
          name: web
        env:
        - name : HBASE_HEAPSIZE
          value: "200"          
        command:
        - sh
        - -c
        - |
          mkdir -p /hbase/logs
          hbase rest start | tee -a /hbase/logs/hbase-thrift2.log
        volumeMounts:
        - name: hbase
          mountPath: /hbase/conf                                     
      volumes:
      - name: hbase
        configMap:
          name: hbase