---
apiVersion: v1
kind: Service
metadata:
  name: hbase-ma
  labels:
    app: hbase-ma
spec:
  ports:
  - port: 16000
    name: rpc
  - port: 16010
    name: web
  clusterIP: None
  selector:
    app: ma
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ma
spec:
  serviceName: hbase-ma
  replicas: 2
  template:
    metadata:
      labels:
        app: ma
    spec:
      containers:
      - name: hbase
        imagePullPolicy: Always
        image: pilchard/hbase
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 16000
          name: rpc
        - containerPort: 16010
          name: web
        env:
        - name : HBASE_HEAPSIZE
          value: "1000"          
        command:
        - sh
        - -c
        - |
          echo "hbase - nofile  32768" > /etc/security/limits.d/hbase.conf
          /etc/init.d/hbase-master start
          tail -f /var/log/hbase/*
        volumeMounts:
        - name: hbase
          mountPath: /etc/hbase/conf          
        - name: hadoop
          mountPath: /etc/hadoop/conf                           
      volumes:
      - name: hbase
        configMap:
          name: hbase
      - name: hadoop
        configMap:
          name: hadoop 
