---
apiVersion: v1
kind: Service
metadata:
  name: hbase-rs
  labels:
    app: hbase-rs
spec:
  ports:
  - port: 16020
    name: rpc
  - port: 16030
    name: web
  clusterIP: None
  selector:
    app: rs
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rs
spec:
  serviceName: hbase-rs
  replicas: 3
  template:
    metadata:
      labels:
        app: rs
    spec:
      containers:
      - name: hbase
        imagePullPolicy: IfNotPresent
        image: pilchard/hbase
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 16020
          name: rpc
        - containerPort: 16030
          name: web
        env:
        - name : HBASE_HEAPSIZE
          value: "500"          
        command:
        - sh
        - -c
        - |
          mkdir -p /hbase/logs
          nohup hbase regionserver start 2>&1 > /hbase/logs/hbase-regionserver.log &
          tail -f /hbase/logs/hbase-regionserver.log
        volumeMounts:
        - name: hbase
          mountPath: /etc/hbase/conf          
        - name: hadoop
          mountPath: /etc/hadoop/conf
      volumes:
      - name: hbase
        configMap:
          name: hbase
      - name: hadoop
        configMap:
          name: hadoop

