apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    alertmanager: main
  name: alertmanager
spec:
  endpoints:
  - port: web
  selector:
    matchExpressions:
    - {key: alertmanager, operator: In, values: [main]}
