apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kafka
  name: kafka
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafkazookeeper
    spec:
      containers:
      - name: kafkazookeeper
        image: kubernetes/heapster_kafka:canary
        env:
          - name: ADVERTISED_PORT
            value: '9092'