---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9092
    targetPort: 9092
  clusterIP: None
  selector:
    app: kf
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kf
  namespace: kube-system
spec:
  serviceName: kafka
  replicas: 3
  template:
    metadata:
      labels:
        app: kf
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-0.zk-headless.default:2181,zk-1.zk-headless.default:2181,zk-2.zk-headless.default:2181"
