apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: kube-system
  labels:
    component: elasticsearch
    role: logstash
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
    role: logstash
  ports:
  - name: http
    port: 9600
    protocol: TCP
