---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  selector:
    app: kf-m
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kf-m
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kf-m
    spec:
      containers:
      - name: kafka
        image: pilchard/kafka-manager
        env:
        - name: APPLICATION_SECRET
          value: "letmein"
        - name: ZK_HOSTS
          value: "zk-0.zk-headless.default:2181,zk-1.zk-headless.default:2181,zk-2.zk-headless.default:2181"
