---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  ports:
  - name: http
    port: 9092
    targetPort: 9092
  clusterIP: None
  selector:
    app: kf
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kf
  namespace: default
spec:
  serviceName: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kf
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-0.zk-headless.default:2181,zk-1.zk-headless.default:2181,zk-2.zk-headless.default:2181"
        - name: KAFKA_JMX_OPTS
          value:  "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=1099"
        - name: JMX_PORT
          value: "1099"
        - name: BROKER_ID_COMMAND
          value: "hostname | awk -F'-' '{print $2}'"
        volumeMounts:
        - name: kf       
          mountPath: /kafka
  volumeClaimTemplates:
  - metadata:
      name: kf
      annotations:
        volume.beta.kubernetes.io/storage-class: slow 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi

