apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  entrypoint: |
    #!/bin/bash

    set -xe

    cp /scripts/config.toml /etc/gitlab-runner/

    # Register the runner
    /entrypoint register --non-interactive \
      --executor kubernetes \
      {{- range .Values.runners.imagePullSecrets }}
      --kubernetes-image-pull-secrets {{ . | quote }} \
      {{- end }}

    cat >> /etc/gitlab-runner/config.toml << EOF
          [[runners.kubernetes.volumes.host_path]]
            name = "hosts"
            host_path = "/etc/hosts"
            mount_path = "/etc/hosts"
            read_only = false
          [[runners.kubernetes.volumes.host_path]]
            name = "docker"
            host_path = "/var/run/docker.sock"
            mount_path = "/var/run/docker.socket"
            read_only = false
    EOF


    # Start the runner
    /entrypoint run --user=gitlab-runner \
      --working-directory=/home/gitlab-runner
  config.toml: |
    concurrent = {{ .Values.concurrent }}
    check_interval = {{ .Values.checkInterval }}
