kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: submit-queue
    target-repo: test-infra
  name: test-infra-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
