apiVersion: v1
kind: Service
metadata:
  labels:
    app: submit-queue
    target-repo: test-infra
  name: test-infra-sq-status
spec:
  ports:
  - name: status
    port: 80
    targetPort: status
  selector:
    app: submit-queue
    target-repo: test-infra
  type: NodePort
