apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress 
  namespace: myapp
spec:
  rules:
  - host: wordpress.kudoop.cn
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog 
  namespace: myapp
spec:
  rules:
  - host: blog.kudoop.cn
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openfass
  namespace: openfaas
spec:
  rules:
  - host: openfass.kudoop.cn
    http:
      paths:
      - backend:
          serviceName: gateway-external
          servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeless
  namespace: kubeless
spec:
  rules:
  - host: kubeless.kudoop.cn
    http:
      paths:
      - backend:
          serviceName: ui
          servicePort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cockpit
  namespace: kube-system
spec:
  rules:
  - host: cockpit.kudoop.cn
    http:
      paths:
      - backend:
          serviceName: kubernetes-cockpit
          servicePort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeapps
  namespace: kubeapps
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kubeapps.kudoop.cn
    http:
      paths:
      - backend:
          serviceName: kubeapps-dashboard-ui
          servicePort: 8080
