apiVersion: v1
kind: Service
metadata:
  name: calico-k8s
  labels:
    k8s-app: calico-node
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: monitor
    port: 9091
  selector:
    k8s-app: calico-node
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: calico-k8s
  labels:
    k8s-app: calico-node
  namespace: monitoring
spec:
  jobLabel: k8s-app
  endpoints:
  - port: monitor
    interval: 30s
    scheme: http
  selector:
    matchLabels:
      k8s-app: calico-node
  namespaceSelector:
    matchNames:
    - kube-system
