apiVersion: v1
kind: Service
metadata:
  name: ingress-k8s
  labels:
    k8s-app: ingress-nginx
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: monitor
    port: 10254
  selector:
    app: ingress-nginx
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-k8s
  labels:
    k8s-app: ingress-k8s
  namespace: monitoring
spec:
  jobLabel: k8s-app
  endpoints:
  - port: monitor
    interval: 30s
    scheme: http
  selector:
    matchLabels:
      k8s-app: ingress-nginx
  namespaceSelector:
    matchNames:
    - kube-system
