apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-loadbalancer
  namespace: kube-system
  labels:
    app: kube-loadbalancer
    version: v1
spec:
  replicas: 1
  selector:
    app: kube-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: kube-loadbalancer
        version: v1
    spec:
    #  nodeSelector:
    #    role: kube-loadbalancer
      containers:
      - image: docker.io/pilchard/servicelb
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
        # All http services
        - containerPort: 80 
          hostPort: 80
          protocol: TCP
        # nginx https
        - containerPort: 8086
          hostPort: 8086 
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          hostPort: 1936
          protocol: TCP
        resources: {}
        args:
        - --tcp-services=monitoring-influxd:8086
        - --namespace=test
      hostNetwork: true

