apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loadbalancer-kube
  labels:
    tier: loadbalancer-kube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: loadbalancer-kube
        version: v1
    spec:
      nodeSelector:
        role: loadbalancer-kube
      hostNetwork: true
      containers:
      - image: docker.io/pilchard/servicelb
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy-kube
        ports:
        # All http services
        - containerPort: 80 
          hostPort: 80
          protocol: TCP
        # monitoring-grafana 
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
        # monitoring-influxdb 
        - containerPort: 8086
          hostPort: 8086
          protocol: TCP
        # haproxy stats
        #- containerPort: 1936
        #  hostPort: 1936
        #  protocol: TCP
        resources: {}
        args:
        - --tcp-services=monitoring-grafana:3000,monitoring-influxdb:8086
        - --namespace=kube-system
