apiVersion: v1
kind: Service
metadata:
  labels:
    app: cherrypick
    target-repo: kubernetes
  name: cherrypick-status
  namespace: default
spec:
  ports:
  - name: status
    port: 80
    targetPort: status
  selector:
    app: cherrypick
  type: LoadBalancer
