apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    app: solr
spec:
  ports:
  - port: 8983
    targetPort: 8983
    name: solr
#  clusterIP: None
  selector:
    app: solr
---
apiVersion: apps/v1beta1
kind: StatefulSet 
metadata:
  name: solr
spec:
  serviceName: solr
  replicas: 1
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - name: solr
        imagePullPolicy: IfNotPresent
        image: pilchard/solr
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 8983
          name: rpc
        env:
        - name: SOLR_ZK_ENSEMBLE
          value: "zk-0.zk-headless:2181,zk-1.zk-headless:2181,zk-2.zk-headless:2181/solr"          
        - name: SOLR_HDFS_HOME
          value: "hdfs://hdfscluster/solr"
        command:
        - sh
        - -c
        - |
          su - hdfs -c "hdfs dfs -ls /solr"
          if [ $? -ne 0 ];then
            su - hdfs -c "hdfs dfs -mkdir /solr"
            su - hdfs -c "hdfs dfs -chown solr:solr /solr"
            su -s /bin/bash -c "solrctl init" solr
          fi
          echo "SOLR_ZK_ENSEMBLE=$SOLR_ZK_ENSEMBLE" >> /etc/default/solr
          echo "SOLR_HDFS_HOME=$SOLR_HDFS_HOME" >> /etc/default/solr
          /etc/init.d/solr-server start
          tail -f /var/log/solr/*
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf                         
      volumes:
      - name: hadoop
        configMap:
          name: hadoop

