---
apiVersion: v1
kind: Service
metadata:
  name: oozie
  labels:
    app: oozie
spec:
  ports:
  - port: 11000
    targetPort: 11000
    name: oozie
  selector:
    app: oozie
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oozie
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oozie
    spec:
      containers:
      - name: oozie
        imagePullPolicy: IfNotPresent
        image: pilchard/oozie
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 11000
          name: rpc
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"          
        command:
        - sh
        - -c
        - |
          mkdir -p /hive/logs
          nohup hive --service metastore 2>&1 > /hive/logs/hive-metastore.log &
          tail -f /hive/logs/hive-metastore.log
        volumeMounts:
        - name: hive
          mountPath: /usr/lib/hive/conf   
        volumeMounts:
        - name: hadoop
          mountPath: /usr/lib/hadoop/conf                         
        volumeMounts:
        - name: oozie
          mountPath: /usr/lib/oozie/conf 
      volumes:
      - name: hive
        configMap:
          name: hive
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
      volumes:
      - name: oozie
        configMap:
          name: oozie

