apiVersion: v1
kind: Service
metadata:
  name: oozie
  labels:
    app: oozie
spec:
  type: NodePort
  ports:
  - port: 11000
    targetPort: 11000
    name: oozie
  selector:
    app: oozie
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oozie
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: oozie
    spec:
      containers:
      - name: oozie
        imagePullPolicy: IfNotPresent
        image: pilchard/oozie
#        resources:
#          requests:
#            cpu: "100m"
        ports:
        - containerPort: 11000
          name: rpc
        env:
        - name : HADOOP_HEAPSIZE
          value: "200"          
        command:
        - sh
        - -c
        - |
          rm -f /etc/oozie/conf/*
          cp -p /tmp/oozie/conf/* /etc/oozie/conf
          /etc/init.d/oozie start
          tail -f /var/log/oozie/*
        volumeMounts:
        - name: hadoop
          mountPath: /etc/hadoop/conf                         
        - name: oozie
          mountPath: /tmp/oozie/conf 
      volumes:
      - name: hadoop
        configMap:
          name: hadoop
      - name: oozie
        configMap:
          name: oozie

